<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo 3 Parte II** | Elementos Básicos de Numpy
**Exercícios**<br> 
[Luiz Aires](https://github.com/luizaires)

---

In [72]:
import numpy as np

### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura em metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [73]:
lista_de_alturas = list(range(170, 190, 5))
lista_de_alturas

[170, 175, 180, 185]

In [74]:
#Parte I
altura_em_centimetros = np.array(lista_de_alturas)
altura_em_centimetros

array([170, 175, 180, 185])

In [75]:
#Parte II
altura_em_metros = altura_em_centimetros*0.01
altura_em_metros

array([1.7 , 1.75, 1.8 , 1.85])

---

### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [76]:
lista_pesos = [70, 75, 80, 85]
pesos =np.array(lista_pesos)
pesos

array([70, 75, 80, 85])

In [90]:
imc = pesos/(altura_em_metros**2)
imc

array([24.22145329, 24.48979592, 24.69135802, 24.83564646])

---

### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros=[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [78]:
#Parte i
dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
nd_financeiros = np.array(dados_financeiros)
nd_financeiros
# Cada elemento do meu array é uma lista com os dados de cada coluna

array([[ 3000,  2500,  1000, 10000],
       [ 1000,  2500,  3000,  5000],
       [ 6000,  5500,  7000, 16000]])

---

In [79]:
#Parte ii
#Não é interressante alterar meus dados originais, principalmente quando se estar rodando células de maneira não sequencial
nd_financeiros_indiv = nd_financeiros.transpose() #transposta da matriz
nd_financeiros_indiv

array([[ 3000,  1000,  6000],
       [ 2500,  2500,  5500],
       [ 1000,  3000,  7000],
       [10000,  5000, 16000]])

In [80]:
# Cada elemento do meu array é uma lista com os dados de cada coluna
print(nd_financeiros_indiv[:,1]) #2ª linha
print(nd_financeiros_indiv[1,:]) #2ª coluna

[1000 2500 3000 5000]
[2500 2500 5500]


----

In [81]:
#Parte iii
#Realizando o cáculo do endividamento total, operando com as colunas da tabela original
custo_fixo, dívida_finan, renda_familiar = nd_financeiros #Atribuindo valores da coluna para respectiva variável
print(custo_fixo)
print(dívida_finan)
print(renda_familiar)

[ 3000  2500  1000 10000]
[1000 2500 3000 5000]
[ 6000  5500  7000 16000]


In [82]:
#Maior clareza no que se que quer calcular
endividamento_total = (custo_fixo+dívida_finan)/renda_familiar
endividamento_total

array([0.66666667, 0.90909091, 0.57142857, 0.9375    ])

---

In [83]:
#Parte iv
#Renda familiar está na 3ª lista (índice 2) e a 3º indivíduo é o 3º elemento(índice 2) dessa lista
nd_financeiros[2][2] = 10000
nd_financeiros

array([[ 3000,  2500,  1000, 10000],
       [ 1000,  2500,  3000,  5000],
       [ 6000,  5500, 10000, 16000]])

In [84]:
#Realizando o cáculo do endividamento total
custo_fixo, dívida_finan, renda_familiar = nd_financeiros
print(custo_fixo)
print(dívida_finan)
print(renda_familiar)

[ 3000  2500  1000 10000]
[1000 2500 3000 5000]
[ 6000  5500 10000 16000]


In [85]:
endividamento_total = (custo_fixo+dívida_finan)/renda_familiar
endividamento_total

array([0.66666667, 0.90909091, 0.4       , 0.9375    ])

---

### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [86]:
# objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)
poi = np.random.poisson(3, 100)
poi

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 0, 3, 3, 2, 8, 2, 3, 3, 3, 0, 4, 4, 2,
       6, 6, 0, 3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3,
       2, 2, 3, 6, 2, 2, 4, 3, 5, 2, 5, 3, 0, 2, 1, 1, 4, 4, 4, 6, 2, 4,
       1, 2, 5, 5, 3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 0, 4, 4, 0, 6, 1,
       3, 4, 2, 5, 4, 5, 5, 3, 4, 6, 8, 2])

In [87]:
#Parte i
bool_zero = np.array(list(map(lambda i: i == 0, poi)))
bool_zero

array([False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [88]:
#Parte ii
sum(bool_zero)

6

In [89]:
#Parte iii
poi_nao_zero = poi[bool_zero == False]
poi_nao_zero

array([3, 3, 6, 2, 4, 5, 4, 4, 2, 3, 3, 2, 8, 2, 3, 3, 3, 4, 4, 2, 6, 6,
       3, 4, 3, 5, 2, 1, 3, 2, 2, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3, 2, 2, 3,
       6, 2, 2, 4, 3, 5, 2, 5, 3, 2, 1, 1, 4, 4, 4, 6, 2, 4, 1, 2, 5, 5,
       3, 4, 1, 4, 1, 1, 7, 1, 2, 1, 3, 7, 4, 4, 6, 1, 3, 4, 2, 5, 4, 5,
       5, 3, 4, 6, 8, 2])

---